sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zhangyu
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJDoyGQEz2xrJ7sQg43
    access-key-secret: fcPGA6OT4PQHgXxxP6PuKEarV3DjU6
    bucket-name: sky-takeaway-zy
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: wx15e1c07e9ad4c305
    secret: 608d61501efbe5959d01a54170620950
  shop:
    address: 江西省九江市彭泽县新星幼儿园
  baidu:
    ak: KjeoaC3tNbUHrz0f62n6Vd9hIKt9CqGf